### ISSUE TITLE
Messenger: timestamps are off by one hour

### ISSUE THREAD

**Issue by paulchen** [RavuAlHemio/VBCBBot-Sharp#5]
The messenger shows wrong timestamps when replaying messages.

Example: message 983816 [1] (written at 2015-01-06 02:34) which was replayed in message 984097 [2] (which shows 2015-01-06 03:34)

[1] https://rueckgr.at/~paulchen/chatbox/?limit=100&id=983816&epoch=1
[2] https://rueckgr.at/~paulchen/chatbox/?limit=100&id=984097&epoch=1

**Comment by RavuAlHemio** [comment]
vBulletin's timezone "support" with its DST "correction" is an unmitigated disaster trying and failing to solve a problem that has been taken care of correctly ages ago by the Unix timezone database.

Log in as bot using browser, wait for correction to complete, log out again. See you again in March!
